lecture3/pystagram/pystagram/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views as blog_views

urlpatterns = [
    url(r'^posts/create/$', blog_views.create_post, name="create_post"),
    url(r'^posts/edit/(?P<pk>[0-9]+)/$', blog_views.edit_post, name='edit_post'),
    url(r'^posts/delete/(?P<pk>[0-9]+)/$', blog_views.delete_post, name='delete_post'),
    url(r'^posts/comment/create/', blog_views.create_comment_post, name='create_post_comment'),
    url(r'^$', blog_views.list_posts),
    url(r'^posts/(?P<pk>[0-9]+)/$', blog_views.post_detail, name='view_post'),
    url(r'^hello_template/$', blog_views.hello_with_template),
    url(r'^admin/', admin.site.urls)
]

lecture3/pystagram/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category')
    tag = models.ManyToManyField('Tag')

    is_model_field = False

    class Meta:
        ordering = ['-created_at','-pk']
        index_together = ['title','created_at']

class Comment(models.Model):
    post = models.ForeignKey(Post)
    content = models.TextField(max_length=500, default=' ')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=40)

class Category(models.Model):
    name = models.CharField(max_length=40)

lecture3/pystagram/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.core.paginator import EmptyPage
from django.shortcuts import redirect

from .models import *
# Create your views here.

def hello(request):
    return HttpResponse('hello world')


def hello_with_template(request):
    return render(request,'hello.html')

def list_posts(request):
    per_page = 2
    try:
        current_page = int(request.GET.get('page',1))
    except ValueError:
        current_page = 1

    #Post.objects.prefetch_related()
    #Post.objects.select_related().prefetch_related()
    posts = Post.objects.prefetch_related().all()

    paginator = Paginator(posts, per_page)
    try:
        pg = paginator.page(current_page)
    except EmptyPage:
        pg = []

    posts = posts[(current_page-1)*2:current_page*per_page]
    return render(request,'list_view.html',{
            'posts':pg
        })

def post_detail(request, pk):
        #post = get_object_or_404(Post, pk=pk)
    try:
        post = Post.objects.select_related().prefetch_related().get(pk=pk)
    except Post.DoesNotExist:
        post = None
        #redirect
    return render(request,'post_detail.html', {
        'post': post,
    })

def create_post(request):
    categories = Category.objects.all()

    if request.method == 'GET':
        pass

    if request.method == 'POST':
        new_post = Post()
        new_post.title = request.POST.get('title')
        new_post.content = request.POST.get('content')

        category_pk = request.POST.get('category')
        post_category = Category.objects.get(pk=category_pk)
        
        new_post.category = post_category

        new_post.save()

        return post_detail(request, new_post.pk)

    return render(request, 'create_post.html', {
        'categories' : categories
    })

def create_comment_post(request):
    if request.method == 'POST':
        try:
            post = Post.objects.get(id=request.POST.get('post_pk'))
        except Post.DoesNotExist:
            return None
        new_comment = Comment()
        new_comment.content = request.POST.get('content')
        
        new_comment.post = post
        new_comment.save()

    return redirect('/posts/{}'.format(post.pk))
    
def edit_post(request, pk):
    categories = Category.objects.all()

    post = Post.objects.get(pk=pk)

    if request.method == 'GET':
        pass

    if request.method == 'POST':
        post = Post.objects.get(pk=pk)        
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')

        category_pk = request.POST.get('category')
        post_category = Category.objects.get(pk=category_pk)
        
        post.category = post_category

        post.save()

        return post_detail(request, post.pk)

    return render(request, 'create_post.html', {
        'categories' : categories,
        'post' : post
    })

def delete_post(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()

    return redirect('/') 

lecture3/pystagram/blog/templates/blog_layout.html
<!DOCTYPE html>

{% load bootstrap3 %}
<html>
    <head>
    <title>{% block page_title %}Welcome to Pystagram {% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script>{% block script_area %} {% endblock %} </script>
    </head>

    <body class="container">
    {% block content %} {% endblock %}
    </body>
</html>

lecture3/pystagram/blog/templates/comment_list.html
{% load bootstrap3 %}

<div class = "comments_box">
{% for comment in comments %}
<div class = "comment_container">
    <div class = "comment_content">{{comment.content }}</div>
    <p><span>Created At </span>{{comment.created_at}}</p>
</div>
{% empty %}
    <p>There is no comment</p>
{% endfor %}
<div class = "comment_create">
    <form method="POST" action="/posts/comment/create/" class="form-horizontal">
    {% csrf_token  %}
    <div class="form-group form-group-sm">
        <!--p>
            <label for="id_title">Title</label>
            <input type="text" name="title" id="id_title"/>
        </p-->
        <input type="hidden" name="post_pk" value="{{post.pk}}">
        <p>
            <textarea name="content"></textarea>
        </p>
        <p>
            {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
        </p>
    </div>
</form>
   
</div>
</div>

lecture3/pystagram/blog/templates/create_post.html
<!-- blog/templates/hello.html -->
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}
<!DOCTYPE Html>
{% block page_title %} {% if post == None %}New Post 
    {% else %}Edit Post{{post.pk}} 
    {% endif %}
    {% endblock %}

{% block script_area %}
$(document).ready(function(){
    $('#category_select').val("{{post.category.pk}}");
    $('#id_title').val("{{post.title}}");
    $('#id_content').html("{{post.content}}");
});
{% endblock %}

{% block content %} 
<form method="POST" action="" class="form-horizontal">
    {% csrf_token  %}
    <div class="form-group form-group-sm">
        <p>
            <select name="category", id="category_select">
            {% for category in categories %}
                <option value="{{category.pk}}">{{category.name}}</option>
            {% endfor %}
            </select>
        </p>
        <p>
            <label for="id_title">Title</label>
            <input type="text" name="title" id="id_title" />
        </p>
        <p>
            <textarea name="content" id="id_content"></textarea>
        </p>
        <p>
            {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
        </p>
    </div>
</form>

{% endblock %}

lecture3/pystagram/blog/templates/hello.html
<!-- blog/templates/hello.html -->
<!DOCTYPE Html>
<html>
    <head>
        <title>Hello, World</title>
        <meta charset="UTF-8" />
    </head>

    <body>
        Hello, Everyone
    </body>
</html>

lecture3/pystagram/blog/templates/list_view.html
<!-- blog/templates/list_view.html -->
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %}Post List{% endblock %}

{% block content %}
    {% for post in posts %}
    <div class="post_container">
        <h3><a href="{% url 'view_post' pk=post.pk %}">{{ post.title }}</a> </h3>
        <div class="post_content">
            {{ post.content }}
        </div>

        <div>
            <p> category : {{post.category.name}} </p>
            <p> createdAt : {{post.created_at}} </p>
    </div>
    {% empty %}
        <p> There is no post </p>
    {% endfor %}
    
    {% bootstrap_pagination posts %}
{% endblock %}

lecture3/pystagram/blog/templates/post_detail.html
<!-- blog/templates/post_detail.html -->
<!DOCTYPE Html>
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %}Post Number {{post.pk}} {% endblock %}

{% block content %} 
    <div class="post_container">
        <h3> {{post.title}} </h3>
        <div class="post_content">
            {{ post.content }}
        </div>

        <div>
            <p> category : {{post.category.name}} </p>

            <p> createdAt : {{post.created_at}} </p>
    </div>

    <div>
        <p><a href="{% url 'edit_post' post.pk %}">Edit</a></p>
        <p><a href="{% url 'delete_post' post.pk %}">Delete</a></p>
    </div>
    
    {% with comments=post.comment_set.all where='post' %}
        {% include 'comment_list.html' %}
    {% endwith %}
      
{% endblock %}